# health_check.py - 健康检查业务逻辑处理器
import psutil
import json
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

class HealthChecker:
    def __init__(self):
        pass

    def perform_check(self):
        """执行健康检查"""
        try:
            result = {
                "status": "success",
                "data": {
                    "cpu": self.check_cpu(),
                    "memory": self.check_memory(),
                    "disk": self.check_disk(),
                    "network": self.check_network()
                },
                "timestamp": datetime.now().isoformat()
            }
            return result
        except Exception as e:
            logger.error(f"健康检查失败: {e}")
            return {
                "status": "error",
                "error": str(e),
                "timestamp": datetime.now().isoformat()
            }

    def check_cpu(self):
        """检查 CPU 使用率"""
        return {
            "usage_percent": psutil.cpu_percent(interval=1),
            "count": psutil.cpu_count()
        }

    def check_memory(self):
        """检查内存使用情况"""
        mem = psutil.virtual_memory()
        return {
            "total": mem.total,
            "available": mem.available,
            "percent": mem.percent
        }

    def check_disk(self):
        """检查磁盘使用情况"""
        disk = psutil.disk_usage('/')
        return {
            "total": disk.total,
            "free": disk.free,
            "percent": disk.percent
        }

    def check_network(self):
        """检查网络状态"""
        net = psutil.net_io_counters()
        return {
            "bytes_sent": net.bytes_sent,
            "bytes_recv": net.bytes_recv
        }

if __name__ == '__main__':
    import sys
    checker = HealthChecker()
    result = checker.perform_check()
    print(json.dumps(result, indent=2))

# Generated by Copilot