#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AR 系统智能启动器 - Python 核心逻辑
版本: 1.0
作者: AI 全栈技术员
最后更新: 2026年2月4日

功能:
- 自动环境检测 (容器 vs 本地)
- 虚拟环境智能管理
- 依赖自动检查和安装
- 路径自动配置
"""

import os
import sys
import json
import subprocess
import platform
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# 导入路径管理器 - Generated by Copilot
try:
    from path_manager import get_path_manager
except ImportError:
    sys.path.insert(0, str(Path(__file__).parent))
    from path_manager import get_path_manager

class ARSystemLauncher:
    """AR 系统智能启动器 - 使用统一路径管理器"""

    def __init__(self):
        # 使用统一的路径管理器
        self.path_mgr = get_path_manager()
        self.project_root = self.path_mgr.project_root
        self.is_container = self._detect_container()
        self.venv_path = self.project_root / ".venv"
        self.requirements_file = self.project_root / "requirements.txt"
        self.monitor_port = 5000

        # 颜色定义 (用于输出)
        self.colors = {
            'RED': '\033[0;31m',
            'GREEN': '\033[0;32m',
            'YELLOW': '\033[1;33m',
            'BLUE': '\033[0;34m',
            'PURPLE': '\033[0;35m',
            'CYAN': '\033[0;36m',
            'NC': '\033[0m'
        }

    def _detect_container(self) -> bool:
        """检测是否在容器中运行"""
        # 检查环境变量
        if os.getenv('AR_CONTAINER') == 'true':
            return True

        # 检查Docker环境
        if Path('/.dockerenv').exists():
            return True

        # 检查容器特定的环境变量
        container_env_vars = ['DOCKER_CONTAINER', 'KUBERNETES_SERVICE_HOST']
        if any(os.getenv(var) for var in container_env_vars):
            return True

        # 检查cgroup
        try:
            with open('/proc/1/cgroup', 'r') as f:
                if 'docker' in f.read().lower():
                    return True
        except:
            pass

        return False

    def log(self, message: str, color: str = 'NC') -> None:
        """输出带颜色的日志"""
        color_code = self.colors.get(color, self.colors['NC'])
        print(f"{color_code}{message}{self.colors['NC']}")

    def run_command(self, cmd: List[str], cwd: Optional[Path] = None,
                   capture_output: bool = False) -> Tuple[int, str, str]:
        """运行命令并返回结果"""
        try:
            result = subprocess.run(
                cmd,
                cwd=cwd or self.project_root,
                capture_output=capture_output,
                text=True,
                timeout=300  # 5分钟超时
            )
            return result.returncode, result.stdout, result.stderr
        except subprocess.TimeoutExpired:
            return -1, "", "命令执行超时"
        except Exception as e:
            return -1, "", str(e)

    def setup_environment_variables(self) -> None:
        """配置环境变量 - 使用PathManager的路径"""
        self.log("🔧 配置环境变量...", "BLUE")

        # 项目路径
        os.environ['AR_PROJECT_PATH'] = str(self.project_root)
        os.environ['AR_PROJECT_ROOT'] = str(self.project_root)  # 新增，便于PathManager使用
        os.environ['PYTHONPATH'] = f"{self.project_root}:{os.environ.get('PYTHONPATH', '')}"

        # 日志配置 - 使用PathManager的日志目录
        os.environ['AR_LOG_LEVEL'] = 'INFO'
        os.environ['AR_LOG_DIR'] = str(self.path_mgr.logs_dir)

        # 服务配置
        os.environ['AR_MONITOR_PORT'] = str(self.monitor_port)
        os.environ['AR_GUI_ENABLED'] = 'true'

        self.log("✅ 环境变量已配置", "GREEN")
        self.log(f"  项目路径: {self.project_root}", "CYAN")
        self.log(f"  日志目录: {self.path_mgr.logs_dir}", "CYAN")
        self.log(f"  监控端口: {self.monitor_port}", "CYAN")

    def setup_virtual_environment(self) -> bool:
        """设置Python虚拟环境"""
        self.log("🔧 设置Python虚拟环境...", "BLUE")

        if not self.venv_path.exists():
            self.log("📦 创建虚拟环境...", "YELLOW")
            returncode, stdout, stderr = self.run_command([
                sys.executable, '-m', 'venv', str(self.venv_path)
            ])

            if returncode != 0:
                self.log(f"❌ 虚拟环境创建失败: {stderr}", "RED")
                return False

            self.log("✅ 虚拟环境创建成功", "GREEN")
        else:
            self.log("✅ 虚拟环境已存在", "GREEN")

        # 激活虚拟环境
        self.log("🔄 激活虚拟环境...", "BLUE")

        activate_script = self.venv_path / "bin" / "activate"
        if not activate_script.exists():
            self.log(f"❌ 虚拟环境激活脚本不存在: {activate_script}", "RED")
            return False

        # 在当前进程中激活虚拟环境
        venv_python = self.venv_path / "bin" / "python"
        venv_pip = self.venv_path / "bin" / "pip"

        if not venv_python.exists():
            self.log(f"❌ 虚拟环境Python可执行文件不存在: {venv_python}", "RED")
            return False

        # 更新PATH
        venv_bin = str(self.venv_path / "bin")
        os.environ['PATH'] = f"{venv_bin}:{os.environ['PATH']}"
        os.environ['VIRTUAL_ENV'] = str(self.venv_path)

        self.log(f"✅ 虚拟环境: {self.venv_path}", "GREEN")

        # 升级pip
        self.log("⬆️  升级pip...", "BLUE")
        returncode, stdout, stderr = self.run_command([str(venv_pip), 'install', '--upgrade', 'pip'])
        if returncode != 0:
            self.log(f"⚠️  pip升级失败，但继续执行: {stderr}", "YELLOW")

        return True

    def parse_requirements(self) -> Tuple[List[str], Optional[str]]:
        """解析requirements.txt文件"""
        if not self.requirements_file.exists():
            raise FileNotFoundError(f"requirements.txt文件不存在: {self.requirements_file}")

        packages = []
        index_url = None

        with open(self.requirements_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue

                if line.startswith('--index-url'):
                    index_url = line.split('--index-url')[1].strip()
                    continue

                # 跳过空行和注释
                if not line:
                    continue

                packages.append(line)

        return packages, index_url

    def check_package_installed(self, package: str) -> bool:
        """检查包是否已安装"""
        # 移除版本约束进行比较
        package_name = package.split('>=')[0].split('==')[0].split('<')[0].strip()

        # 特殊处理torch包
        if package_name.lower() in ['torch', 'torchvision', 'torchaudio']:
            # 检查torch相关包的实际导入名
            if package_name.lower() == 'torch':
                import_name = 'torch'
            elif package_name.lower() == 'torchvision':
                import_name = 'torchvision'
            elif package_name.lower() == 'torchaudio':
                import_name = 'torchaudio'
            else:
                import_name = package_name
        else:
            import_name = package_name

        returncode, stdout, stderr = self.run_command([
            sys.executable, '-c', f'import {import_name}'
        ], capture_output=True)

        return returncode == 0

    def install_dependencies(self) -> bool:
        """检查并安装依赖"""
        self.log("🔍 检查Python依赖...", "BLUE")

        try:
            required_packages, index_url = self.parse_requirements()
        except Exception as e:
            self.log(f"❌ 解析requirements.txt失败: {e}", "RED")
            return False

        missing_packages = []
        total_packages = len(required_packages)

        for package in required_packages:
            package_name = package.split('>=')[0].split('==')[0].split('<')[0].strip()

            if self.check_package_installed(package_name):
                self.log(f"✅ {package_name}", "GREEN")
            else:
                self.log(f"📦 {package_name} (待安装)", "YELLOW")
                missing_packages.append(package)

        if not missing_packages:
            self.log(f"✅ 所有依赖已安装 ({total_packages}/{total_packages})", "GREEN")
            return True

        self.log(f"📥 安装缺失依赖 ({len(missing_packages)}/{total_packages})...", "BLUE")

        # 构建pip install命令
        pip_cmd = [sys.executable, '-m', 'pip', 'install']

        # 特殊处理torch包
        torch_packages = []
        other_packages = []

        for package in missing_packages:
            if 'torch' in package.lower():
                torch_packages.append(package)
            else:
                other_packages.append(package)

        # 如果没有在requirements.txt中找到torch包，手动添加
        if not torch_packages:
            torch_packages = ['torch>=2.2.2', 'torchvision>=0.17.2', 'torchaudio>=2.2.2']

        # 先安装非torch包
        if other_packages:
            cmd = pip_cmd + other_packages
            self.log(f"执行命令: {' '.join(cmd)}", "CYAN")
            returncode, stdout, stderr = self.run_command(cmd, capture_output=True)
            if returncode != 0:
                self.log(f"⚠️  非torch包安装失败: {stderr}", "YELLOW")
                self.log(f"stdout: {stdout}", "YELLOW")
            else:
                self.log("✅ 非torch包安装成功", "GREEN")

        # 单独安装torch包
        if torch_packages:
            torch_cmd = pip_cmd + ['--index-url', 'https://download.pytorch.org/whl/cpu'] + torch_packages
            self.log(f"执行torch命令: {' '.join(torch_cmd)}", "CYAN")
            returncode, stdout, stderr = self.run_command(torch_cmd, capture_output=True)
            if returncode != 0:
                self.log(f"⚠️  torch包安装失败: {stderr}", "YELLOW")
                self.log(f"torch stdout: {stdout}", "YELLOW")
                self.log("   尝试备用安装方式...", "YELLOW")
                # 尝试简单安装
                simple_torch_cmd = pip_cmd + ['torch', 'torchvision', 'torchaudio', '--index-url', 'https://download.pytorch.org/whl/cpu']
                self.log(f"执行备用torch命令: {' '.join(simple_torch_cmd)}", "CYAN")
                returncode2, stdout2, stderr2 = self.run_command(simple_torch_cmd, capture_output=True)
                if returncode2 != 0:
                    self.log(f"⚠️  备用torch安装也失败: {stderr2}", "YELLOW")
                    self.log(f"备用torch stdout: {stdout2}", "YELLOW")
                else:
                    self.log("✅ 备用torch安装成功", "GREEN")

        # 检查最终安装结果
        final_missing = []
        for package in missing_packages:
            package_name = package.split('>=')[0].split('==')[0].split('<')[0].strip()
            if not self.check_package_installed(package_name):
                final_missing.append(package_name)

        if not final_missing:
            self.log("✅ 依赖安装成功", "GREEN")
            return True
        else:
            self.log(f"⚠️  以下包安装失败: {', '.join(final_missing)}", "YELLOW")
            self.log("   系统将继续运行，但某些功能可能受限", "YELLOW")
            return True

    def start_services(self) -> bool:
        """启动所有服务"""
        self.log("🚀 启动完整系统...", "BLUE")

        # 启动监控服务
        self.log("1. 启动监控服务...")
        monitor_cmd = [
            sys.executable, str(self.project_root / "src" / "backend" / "monitor_app.py")
        ]

        try:
            monitor_process = subprocess.Popen(
                monitor_cmd,
                cwd=self.project_root,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )
            self.log(f"✅ 监控服务已启动 (PID: {monitor_process.pid})", "GREEN")
        except Exception as e:
            self.log(f"❌ 监控服务启动失败: {e}", "RED")
            return False

        # 等待监控服务启动
        import time
        time.sleep(3)

        # 检查监控服务是否启动成功
        try:
            import requests
            response = requests.get(f"http://0.0.0.0:{self.monitor_port}/health", timeout=5)
            if response.status_code == 200:
                self.log("✅ 监控服务健康检查通过", "GREEN")
            else:
                self.log(f"⚠️  监控服务响应异常: {response.status_code}", "YELLOW")
        except ImportError:
            self.log("⚠️  requests模块未安装，跳过健康检查", "YELLOW")
            # 简单检查进程是否还在运行
            if monitor_process.poll() is None:
                self.log("✅ 监控服务进程运行中", "GREEN")
            else:
                self.log("❌ 监控服务进程已退出", "RED")
                return False
        except:
            self.log("⚠️  监控服务健康检查失败，但继续执行", "YELLOW")

        # 启动GUI界面
        self.log("2. 启动GUI界面...")
        gui_cmd = [
            sys.executable, str(self.project_root / "src" / "gui.py")
        ]

        try:
            gui_process = subprocess.Popen(
                gui_cmd,
                cwd=self.project_root,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )
            self.log(f"✅ GUI界面已启动 (PID: {gui_process.pid})", "GREEN")
        except Exception as e:
            self.log(f"❌ GUI界面启动失败: {e}", "RED")
            return False

        # 启动自动化监控
        self.log("3. 启动自动化监控...")
        self._start_automated_monitoring()

        # 启动实时状态监控
        self.log("4. 启动实时状态监控...")
        self._start_realtime_monitoring()

        # 打开浏览器
        self.log("5. 打开浏览器...")
        self._open_browser(f"http://0.0.0.0:{self.monitor_port}")

        self.log("🎉 完整系统启动成功！", "GREEN")
        self.log(f"📊 监控页面: http://0.0.0.0:{self.monitor_port}", "CYAN")
        self.log("🖥️  GUI界面已启动", "CYAN")
        self.log("📈 自动化监控已启动", "CYAN")
        self.log("🌐 浏览器已自动打开", "CYAN")

        return True

    def _start_automated_monitoring(self) -> None:
        """启动自动化监控"""
        monitor_scripts = [
            ("scripts/monitor/monitor.py", ["--json", "--interval", "30"]),
            ("scripts/monitor/api_health_check.py", ["--interval", "60"]),
            ("scripts/monitor/deployment_progress.py", ["--watch"])
        ]

        for script_path, args in monitor_scripts:
            script_file = self.project_root / script_path
            if script_file.exists():
                try:
                    cmd = [sys.executable, str(script_file)] + args
                    process = subprocess.Popen(
                        cmd,
                        cwd=self.project_root,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE
                    )
                    self.log(f"✅ {script_path} 已启动 (PID: {process.pid})", "GREEN")
                except Exception as e:
                    self.log(f"⚠️  {script_path} 启动失败: {e}", "YELLOW")

    def _start_realtime_monitoring(self) -> None:
        """启动实时状态监控"""
        status_file = self.project_root / ".ar_system_status"

        # 创建初始状态文件
        initial_status = {
            "status": "running",
            "timestamp": int(time.time()),
            "services": {
                "monitor": "starting",
                "gui": "starting",
                "api": "unknown"
            },
            "health": {
                "overall": "starting"
            }
        }

        with open(status_file, 'w') as f:
            json.dump(initial_status, f, indent=2)

        self.log("✅ 实时状态监控已启动", "GREEN")

    def _open_browser(self, url: str) -> None:
        """打开浏览器"""
        browsers = [
            ("google-chrome", ["--new-window", url]),
            ("chromium-browser", ["--new-window", url]),
            ("firefox", ["--new-window", url]),
            ("safari", ["--new-window", url]),
            ("xdg-open", [url])
        ]

        for browser, args in browsers:
            try:
                subprocess.run([browser] + args, check=True, timeout=5)
                self.log(f"✅ 浏览器已打开: {url}", "GREEN")
                return
            except:
                continue

        self.log(f"⚠️  未找到可用浏览器，请手动打开: {url}", "YELLOW")

    def run(self) -> bool:
        """主运行逻辑"""
        try:
            # 显示环境信息
            env_type = "🐳 容器环境" if self.is_container else "🏠 本地环境"
            venv_status = "✅ 存在" if self.venv_path.exists() else "❌ 不存在"

            self.log(f"📋 环境检测结果:", "PURPLE")
            self.log(f"  运行环境: {env_type}", "CYAN")
            self.log(f"  虚拟环境: {venv_status}", "CYAN")
            self.log(f"  项目路径: {self.project_root}", "CYAN")

            # 配置环境变量
            self.setup_environment_variables()

            # 处理虚拟环境
            if not self.setup_virtual_environment():
                return False

            # 检查并安装依赖
            if not self.install_dependencies():
                return False

            # 启动所有服务
            if not self.start_services():
                return False

            return True

        except Exception as e:
            self.log(f"❌ 启动过程中发生错误: {e}", "RED")
            import traceback
            traceback.print_exc()
            return False


def main():
    """主函数"""
    launcher = ARSystemLauncher()
    success = launcher.run()
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()